# Generated by Django 2.2 on 2019-03-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BootCRUDApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagesellmodel',
            name='image',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
